### ISSUE TITLE
[FEATURE] Authentication with Google or Github for easy login/register for users 

### ISSUE THREAD

**Issue by Trishank-K** [Dipeshdahiya/Remoteflow#23]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

At login and signup page add a  google or github authentication button, using which users can easily login/register into the website.

### Proposed Solution

Will add Github and Google providers clicking upon it will create a session with google or github oauth and authenticate, so the user dosen't need to always enter his/her account details.
The database Schema will also be refactored to allow oauth users to login or sign up

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- Use the NextAuth.js Library to add providers
- Modify the database Schema to allow access to users with Oauth Authentication

**Comment by Dipeshdahiya** [comment]
I have assigned this issue to you , make sure the buttons has the basic coloring which is black and white

**Comment by Trishank-K** [comment]
On it1
