### ISSUE TITLE
[FEATURE] Changing the old twitter logo (bird logo) to new one 

### ISSUE THREAD

**Issue by vipul-dixit-2004** [Dipeshdahiya/Remoteflow#25]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The footer section contains an outdated Twitter logo, which needs to be updated.

### Proposed Solution

The proposed solution is to replace the old <PiTwitterLogoFill /> component with the updated <RiTwitterXLine /> component in the footer section.

### Screenshots

![image](https://github.com/user-attachments/assets/217e65a7-421a-4ad2-885e-a6d1e7004e2e)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Edit the ```components/Footer.jsx``` file 
- Delete the import statement for   ```<PiTwitterLogoFill/>```
- Add new import statement for ```<RiTwitterXFill />```
- Add ```<RiTwitterXFill />``` component in the footer while preserving all previous styles as they were.

**Comment by vipul-dixit-2004** [comment]
Thank you, @Dipeshdahiya, for assigning this issue. I have submitted the pull request, please review and let me know what changes you want.

**Comment by Dipeshdahiya** [comment]
i need no further changes to the landing page , if you want you can contribute to the community page , login page or workspace.
Basically workspace need many changes if you like to contribute on that page please tell me i give you the list i know so make it easy for you

**Comment by vipul-dixit-2004** [comment]
@Dipeshdahiya okay i will look towards it then...
