### ISSUE TITLE
Want to add password toggling feature in Signin / signup page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Dipeshdahiya/Remoteflow#3]
I want to add a password toggling feature so that user can see or hide the password when clicking on eye icon

https://github.com/user-attachments/assets/ecb553df-4a48-4871-b7fa-826ec82658aa

**Comment by vishal-kumar3** [comment]
Hey @Ayushmaanagarwal1211 , Assign this issue to me under hacktoberfest, i will work on it.

**Comment by Ayushmaanagarwal1211** [comment]
@vishal-kumar3 Hii bro actually i am also a contributor i want to work on that

**Comment by Dipeshdahiya** [comment]
@vishal-kumar3 their are many issues on the workboard page you simply pick other issue and i will assign you for that

**Comment by vishal-kumar3** [comment]
@Dipeshdahiya Can you explain me about this project. 
And please open some issues that you feel should me fixed or feature to be added.
What techstack you have used?

**Comment by Dipeshdahiya** [comment]
@vishal-kumar3 in the workspace page 
Profile button is not done yet , it is done but not working you can create a profile block similar to Help & support 
or
Similarly for the setting button in the right-menu
or
The Speaker button is still in development as it is working for now but stopped within 15 to 16 sec even if the notes is not completed to read
or 
Their is a issue when you click on the 3 dots in the right of the new notebook , you will see a block allowing for edit and delete
, just simpaly work any of the button as they also still in work 

their are many other pending works on that page just go ahead simply work on any of it
