### ISSUE TITLE
[BUG] <description> I have a problem when i click on the option Learn More it doesn't navigate to any window.

### ISSUE THREAD

**Issue by PrashantChoudhary13579** [Dipeshdahiya/Remoteflow#42]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

live website

### Version of website/mobile (for example "v1.2.3")

v

### Description

The link titled "Learn More" is currently not functioning. Clicking on it results nowhere . This issue prevents users from learning more about RemoteFlow. Please investigate and update the link to a working URL.

### Steps to Reproduce

1. Go to the home page where the "Learn More" link is located.
2. Click on the link.
3. Observe that the link does not lead to the expected content.

### Screenshots

https://github.com/user-attachments/assets/b461a27b-8823-4025-826b-99d1a9e65a87

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I want to work on this issue please assign me this.

**Comment by Dipeshdahiya** [comment]
@PrashantChoudhary13579 i have assigned the issue to you make sure to complete on time
