### ISSUE TITLE
No Page Designed For User Profile

### ISSUE THREAD

**Issue by rishyym0927** [Dipeshdahiya/Remoteflow#7]
Hey @Dipeshdahiya 

I can create a user profile page for you website matching the design. Please assign this issue to me under hactoberfest label

**Comment by Dipeshdahiya** [comment]
This will be very helpful , you can design a new page or create a block which appears in the middle of the workspace when clicked , similarly as the Trash button and the Help & Support button.

**Comment by Dipeshdahiya** [comment]
I am assigning this issue to you
